第12回課題の提出
tushiko23/tushima-raisetech-task pull request #13
Opened 2024-11-12 14:31 UTC by tushiko23

お世話になります。　第12回課題を提出させていただきます。
お手隙の際にご確認どうぞよろしくお願いします！

2024-11-13 13:10 UTC, MasatoshiMizumoto requested changes
コメント入れた部分が完了すればOKなので、ご対応お願いします！！

2024-11-13 13:10 UTC, MasatoshiMizumoto commented on cloudformation/lecture10-alb.yml
EOFのエラー検知していますのでご対応ください！

2024-11-13 13:10 UTC, MasatoshiMizumoto commented on cloudformation/lecture10-ec2.yml
EOFのエラー検知していますのでご対応ください！

2024-11-13 13:10 UTC, MasatoshiMizumoto commented on cloudformation/lecture10-rds.yml
EOFのエラー検知していますのでご対応ください！

2024-11-13 13:10 UTC, MasatoshiMizumoto commented on cloudformation/lecture10-s3.yml
EOFのエラー検知していますのでご対応ください！

2024-11-13 13:10 UTC, MasatoshiMizumoto commented on cloudformation/lecture10-sg.yml
EOFのエラー検知していますのでご対応ください！

2024-11-16 10:25 UTC, tushiko23 reviewed
お疲れ様です！
修正いたしましたので、ご確認よろしくお願いします！

2024-11-16 10:25 UTC, tushiko23 commented on cloudformation/lecture10-alb.yml
かしこまりました！
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 10:25 UTC, tushiko23 commented on cloudformation/lecture10-ec2.yml
かしこまりました！
IAMrole作成の46行目、statement - Effect: "allow"の - と Effectの間が１つ下がっていましたので修正しました。
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 10:25 UTC, tushiko23 commented on cloudformation/lecture10-s3.yml
かしこまりました！
組み込み関数importvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 10:30 UTC, tushiko23 commented on cloudformation/lecture10-rds.yml
かしこまりました！
RDS→サブネットグループの記述から、サブネットグループ→RDSの記述に変更しました！
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 10:38 UTC, tushiko23 commented on cloudformation/lecture10-sg.yml
かしこまりました！
114行目のSG3Ingress1の記述が110行目のTagsの前に来ていたので、修正しました。
組み込み関数importvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 10:47 UTC, tushiko23 reviewed
かしこまりました！
114行目のSG3Ingress1の記述が110行目のTagsの前に来ていたので、修正しました。
組み込み関数importvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:20 UTC, tushiko23 reviewed
お世話になります。
EOFエラー検知の対応をいたしましたのでご確認よろしくお願いします！
主な修正項目といたしましては、
・リソースの記述のインデントの修正(sg,ec2のiamロール)
・パラメータ値・組み込み関数の記述に "" を付与(全般)
・resourceの記述をコメント上から下に訂正(全般)
・行終端を処理するようGitを設定する(全般)
　[こちら参照](https://docs.github.com/ja/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)
　です。
　ご確認よろしくお願いします！

また、修正後のymlテンプレートを用いてcircleciのジョブ確認もエビデンス画像としてこちらのレビューに追加いたしましたので、ご確認よろしくお願いします！

![Screenshot 2024-11-16 20 19 04](https://github.com/user-attachments/assets/aad453db-6f6c-4183-91f7-5c0bde52cfff)

2024-11-16 11:20 UTC, tushiko23 commented on cloudformation/lecture10-alb.yml
かしこまりました！
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:20 UTC, tushiko23 commented on cloudformation/lecture10-ec2.yml
かしこまりました！
IAMrole作成の46行目、statement - Effect: "allow"の - と Effectの間が１つ下がっていましたので修正しました。
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:20 UTC, tushiko23 commented on cloudformation/lecture10-rds.yml
かしこまりました！
RDS→サブネットグループの記述から、サブネットグループ→RDSの記述に変更しました！
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:20 UTC, tushiko23 commented on cloudformation/lecture10-s3.yml
かしこまりました！
組み込み関数importvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:20 UTC, tushiko23 commented on cloudformation/lecture10-sg.yml
かしこまりました！
114行目のSG3Ingress1の記述が110行目のTagsの前に来ていたので、修正しました。
組み込み関数importvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:40 UTC, tushiko23 commented on cloudformation/lecture10-alb.yml
かしこまりました！
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:40 UTC, tushiko23 commented on cloudformation/lecture10-ec2.yml
かしこまりました！
IAMrole作成の46行目、statement - Effect: "allow"の - と Effectの間が１つ下がっていましたので修正しました。
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:40 UTC, tushiko23 commented on cloudformation/lecture10-rds.yml
かしこまりました！
RDS→サブネットグループの記述から、サブネットグループ→RDSの記述に変更しました！
パラメータ値及び組み込み関数subとimportvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:41 UTC, tushiko23 commented on cloudformation/lecture10-s3.yml
かしこまりました！
組み込み関数importvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 11:41 UTC, tushiko23 commented on cloudformation/lecture10-sg.yml
かしこまりました！
114行目のSG3Ingress1の記述が110行目のTagsの前に来ていたので、修正しました。
組み込み関数importvalue後の値を""囲い修正しました。
また、行終端を処理するようGitを設定して、修正しました！
ご確認よろしくお願いします！

2024-11-16 13:24 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-11-16 13:53 UTC, merged