第14回課題にて、README.mdを作成しましたので確認よろしくお願いします！
tushiko23/tushima-raisetech-task pull request #17
Opened 2024-12-28 14:35 UTC by tushiko23

お世話になります！
リポジトリのREADME.mdを作成しましたのでご確認よろしくお願いします！

2024-12-31 06:16 UTC, MasatoshiMizumoto reviewed
コメントしていきます！

> 全体

まず全体として「長いな」と思います！
READMEは「README 1ST」と捉えられるくらい、「絶対にこれだけは見ておいて」がコンセプトで、そう考えると、伝えたいなら別冊が良いと私は考えます！

> 自動化構成の解説

見てもらいたい人の属性やREADMEの位置付けを考えたときに、情報量が多すぎかなと思いました！前述のとおり別冊で良いかなと！

> インフラ構成の解説

学習の中でアーキテクチャ設計、サービス選定はしていない認識なので、選定理由と書いてしまっている部分は誤解を与えるかなと思いました！
解説なら解説に留めましょう！

> 学習記録

「Buildupでの日々の学習記録」はちょっとわかりにくいです！
履歴書や経歴書で補足しているならこの限りではないですが、READMEへいきなり飛んできた人はちょっと戸惑いますね！

> その他

私なら対エンジニアを意識するので、使った言語やライブラリのバージョン、デプロイ手順を書いちゃいます！
むしろ今書いてもらっていることはほぼREADMEに載せないというか、上記以外は学習記録の表くらいかもですね！

参考にしてみてください！

2025-01-05 13:19 UTC, tushiko23 commented
お世話になります！　大変お待たせいたしました！　
いただいたコメントを参考にREADMEを修正いたしましたのでご確認よろしくお願いします！
修正し、追記した内容は以下になります。

1. Railsアプリケーションに使用した言語
2. Railsアプリケーションに使用した主なライブラリの種類とバージョン
3. 自動化の際のデプロイ手順

なお、コメントいただいていた最初に記述した箇所の修正は以下でさせていただきました！


> 自動化・インフラ構成の解説
別冊 lecture13/README_NOTE.md ファイルにて別冊で作成しました。構成の解説のみ記述させていただきました。
 
> 学習記録
 「Buildupでの日々の学習記録」は履歴書や経歴書で補足したうえで、掲載しようと思います！

2025-01-05 15:07 UTC, MasatoshiMizumoto requested changes
軽微ですがコメント入れております！
よろしくお願いします！！

2025-01-05 15:07 UTC, MasatoshiMizumoto commented on README.md
> +* 今回はオンラインプログラミングスクールRaiseTechの講師の方が作成してくださったアプリケーションを使用します。
RaiseTechは「エンジニアリングスクール」ですね！

2025-01-05 15:07 UTC, MasatoshiMizumoto commented on README.md
> +## オンラインプログラミングスクールRaiseTechでの学習記録
RaiseTechは「エンジニアリングスクール」ですね！

2025-01-06 01:39 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2025-01-06 12:10 UTC, merged